### ISSUE TITLE
Batch: Simpler method signature?

### ISSUE THREAD

**Issue by fmaul** [jgoldhammer/alfresco-jscript-extensions#1]
I think it would be good to be able to run simply:

```javascript
batch.runForNodes(nodes, processorFunction) or
batch.runForQuery(query, processorFunction) 
```

and having batchName, numberOfThreads, numberOfProcessedItems using defaults.

Is it possible to have a syntax like this?:

```javascript
batch.runForNodes({
  batchName : "someName",
  numberOfThreads : 4,
  numberOfProcessedItems : 10,
  nodes : someNodesArray, 
  processorFunction : function() {...}, 
  runAsSystem : true
});
```

**Comment by jgoldhammer** [comment]
For the syntactic sugar version, I recommend https://github.com/ciber/alfresco-js-batch-executer. I will ask him to join my project here to publish it as one extension instead of two...

**Comment by jgoldhammer** [comment]
I have integrated the project into this project.
