### ISSUE TITLE
update addons.alfresco.com information

### ISSUE THREAD

**Issue by jgoldhammer** [jgoldhammer/alfresco-jscript-extensions#10]

**Comment by douglascrp** [comment]
You should change mainly the supported versions, as this is no more compatible with 5.0 because of the dependency on org.alfresco.service.cmr.repository.DeleteLinksStatusReport
This class, at least by the information inside the class, is there since version 5.1.

**Comment by douglascrp** [comment]
@jgoldhammer me again.

I was able to use the addon on 5.0 by simply commenting the scriptLinkService bean
https://github.com/jgoldhammer/alfresco-jscript-extensions/blob/master/src/main/resources/alfresco/module/alfresco-jscript-extension/module-context.xml#L106

**Comment by jgoldhammer** [comment]
@douglascrp Thanks for reporting the error.
Please track https://github.com/jgoldhammer/alfresco-jscript-extensions/issues/11
