### ISSUE TITLE
amp file appears to have unnecessary jars in it

### ISSUE THREAD

**Issue by binduwavell** [jgoldhammer/alfresco-jscript-extensions#13]
The 1.2-4.2 amp file includes the following jars. I assume none are required for a release build and hence this bloats the repository and also could cause jar versioning issues.

```
jetty-continuation-7.4.0.v20110414.jar
jetty-security-7.4.0.v20110414.jar
jetty-util-7.4.0.v20110414.jar
spring-core-3.2.17.RELEASE.jar
args4j-2.0.16.jar                       
jetty-http-7.4.0.v20110414.jar          
jetty-server-7.4.0.v20110414.jar    
junit-remote-3.jar              
spring-test-3.2.17.RELEASE.jar
commons-logging-1.2.jar                 
jetty-io-7.4.0.v20110414.jar            
jetty-servlet-7.4.0.v20110414.jar   
slf4j-api-1.7.7.jar
```

**Comment by jgoldhammer** [comment]
I will check that. So this is only included in the 1.2-4.2.amp, right?

**Comment by jgoldhammer** [comment]
Ok, all versions are involved. I will play with the pom.xml a little bit and see how I can avoid that.
Thanks...

**Comment by jgoldhammer** [comment]
I have fixed it
![image](https://cloud.githubusercontent.com/assets/3872101/20192600/d0e875c0-a78a-11e6-9373-26949a62f77a.png)
