### ISSUE TITLE
Version matrix

### ISSUE THREAD

**Issue by binduwavell** [jgoldhammer/alfresco-jscript-extensions#14]
I just did some basic smoke testing and 1.3.1 worked with Alfresco 5.0.d, 5.0.1, 5.1.e and 5.1. The README seems to indicate that version 1.3.1 of the amp should be used for Alfresco prior to 5.1.a and that version 1.3 of the amp should be used for 5.1.a and above.

I'm having a hard time figuring out what the travis tests are actually telling us. I'd love to have a single version for Alfresco 5.0 and 5.1 (4.x not supported by yeoman generator.) Am I safe to use 1.3.1 for 5.0 and 5.1?

Thanks!

**Comment by jgoldhammer** [comment]
Version 1.3.1 is safe for all versions. 

How should I separate root objects for different Alfresco versions? I don´t want to introduce reflection here, but I think it is the only way to cope with it...

**Comment by jgoldhammer** [comment]
Is that ok for you, @binduwavell ? I will close the ticket in a few days...

**Comment by jgoldhammer** [comment]
Closing now.
