### ISSUE TITLE
Version v1.2-4.2 not working due to version numbering

### ISSUE THREAD

**Issue by fmaul** [jgoldhammer/alfresco-jscript-extensions#15]
The version number "v1.2-4.2" is an invalid Alfresco module version - it must not have the dash in the version number. Alfresco 4.2 failes on startup with an error message. Changing the version to "1.2" works.

It would be good to know if the newer version also work with the older 4.2

**Comment by jgoldhammer** [comment]
No, the newer versions like 1.3 does not work with Alfresco 4.2. I will remove the old branch as Version 4.2 is not widely used anymore.
