### ISSUE TITLE
NativeJavaObject must be unwrapped

### ISSUE THREAD

**Issue by lutzhorn** [jgoldhammer/alfresco-jscript-extensions#16]
If the array of nodes is build like this

````javascript
var nodes = [];
var node = search.findNode("workspace://SpacesStore/...");
nodes.push(node);
````
the call to `runForNodes` fails with a `ClassCastException`. On the line

````java
ScriptNode scriptNode = (ScriptNode) scriptNodes.get(index, null);
````

the cast to `ScriptNode` fails because the object is an instance of `org.mozilla.javascript.NativeJavaObject`. The method `.unwrap()` must be called on this native object before the result can be cast to a `ScriptNode`.

I will prepare a PR to fix this.

**Comment by jgoldhammer** [comment]
Thanks for your bug report. Waiting for a clean pull request to merge. Thanks
