### ISSUE TITLE
Release 1.6

### ISSUE THREAD

**Issue by lutzhorn** [jgoldhammer/alfresco-jscript-extensions#20]
Hi @jgoldhammer, could you please release version 1.6? Deploying Maven snapshots in production environments is something I'd like to avoid.

**Comment by jgoldhammer** [comment]
I have released version 1.7 because I have made a little mistake.
Currently it is not available in Maven repositories because of the delayed staging process of Nexus Sonatype.

**Comment by lutzhorn** [comment]
Thanks!
